[build]
command = "npm install && npm run prod && composer install --no-dev --prefer-dist --no-interaction && vendor/bin/jigsaw build production"
publish = "build_production"

[build.environment]
PHP_VERSION = "8.1"
NODE_VERSION = "18"